---
ntp_server: 10.9.1.70
dns_server: 10.9.1.1
zabbix_server: 10.9.1.70
zabbix_agent_host_metadata_group: k112
zabbix_agent_host_metadata_tag: k8s_k112
master_float_ip: 10.9.1.5
k8s_kubeadm_ignore_preflight_errors: NumCPU,Mem
use_nexus: true
nexus_url: http://10.9.1.70:8081
nexus_docker_registry: 10.9.1.70:8082
nexus_elastic_registry: 10.9.1.70:8083
nexus_k8s_registry: 10.9.1.70:8084

k8s_pod_subnet: 10.9.16.0/20
k8s_service_subnet: 10.9.2.0/24
