---
etcd_version: v3.5.17
etcd_download_base_url: https://github.com/etcd-io/etcd/releases/download
etcd_install_dir: /usr/local/bin
etcd_config_dir: /etc/etcd
etcd_data_dir: /var/lib/etcd
etcd_user: etcd
etcd_group: etcd
etcd_client_port: 2379
etcd_peer_port: 2380
etcd_cluster_token: etcd-cluster
etcd_initial_cluster_state: new
etcd_selected_hosts: "{{ hosts | default(ansible_play_hosts_all | join(',')) }}"

