---
kubernetes_apt_version: v1.30
kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl
kubernetes_apt_upstream_url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_apt_version }}/deb/"
kubernetes_apt_remote_url: >-
  {{
    nexus_url ~ '/repository/kubernetes-' ~
    (kubernetes_apt_version | replace('.', '-')) ~ '-proxy/'
    if use_nexus | default(false) | bool
    else kubernetes_apt_upstream_url
  }}
kubernetes_apt_key_url: "{{ kubernetes_apt_remote_url }}Release.key"
kubernetes_apt_key_tmp: /tmp/kubernetes-apt-release.key
kubernetes_apt_keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
kubernetes_apt_repo: >-
  deb [signed-by={{ kubernetes_apt_keyring }}]
  {{ kubernetes_apt_remote_url }} /
kubernetes_force_ipv4: true
kubernetes_apt_proxy_effective: ""
kubernetes_apt_proxy_conf: /etc/apt/apt.conf.d/90kubernetes-proxy
