---
# Получене сертификата letsencrypt для домена и всех его поддоменов через API reg.ru
# Внимание! Перед запуском нужно добавить в настройках акаунта reg.ru IP VDS машны,
# для которой добавляется сертификат
# https://www.reg.ru/user/account/#/settings/api/ Диапазоны IP-адресов: x.x.x.x/32
# 0.0.0.0/0 не работает :-(
# Запускаеть нужно один раз - автообноление здесь не выполняется, чтобы не нагромождать плейбук
- name: Run Docker container with Ubuntu 24.04 and Certbot Regru
  hosts: all
  become: yes

  vars:
    docker_network_name: docker-net
    docker_network_subnet: 172.20.0.0/16
    docker_network_range: 172.20.240.0/20

  tasks:
    - name: Include regru secrets
      include_vars: ../secrets/regru_secrets.yml

    - name: Include letsencrypt secrets
      include_vars: ../secrets/letsencrypt_secrets.yml

    - name: Ensure Docker network exists
      community.docker.docker_network:
        name: "{{ docker_network_name }}"
        ipam_config:
          - subnet: "{{ docker_network_subnet }}"
            iprange: "{{ docker_network_range }}"

    - name: Ensure /etc/letsencrypt directory exists on the host
      file:
        path: /etc/letsencrypt
        state: directory
        mode: '0755'

    - name: Run Docker container with Ubuntu 24.04 and mount /etc/letsencrypt
      community.docker.docker_container:
        name: certbot_container
        image: ubuntu:24.04
        state: started
        volumes:
          - /etc/letsencrypt:/etc/letsencrypt
        command: sleep infinity
        networks:
          - name: "{{ docker_network_name }}"
        restart_policy: unless-stopped

    - name: Install apt-get update
      community.docker.docker_container_exec:
        container: certbot_container
        command: apt-get update

    - name: Install python3-pip in container
      community.docker.docker_container_exec:
        container: certbot_container
        command: apt-get install -y python3-pip

    - name: Install certbot-regru via pip in container
      community.docker.docker_container_exec:
        container: certbot_container
        command: pip3 install certbot-regru --break-system-packages

    - name: Create regru.ini on host in /etc/letsencrypt
      copy:
        dest: /etc/letsencrypt/regru.ini
        content: |
          dns_username = {{ regru_login }}
          dns_password = {{ regru_passwd }}
        mode: '0600'

    - name: Set permissions for regru.ini file
      community.docker.docker_container_exec:
        container: certbot_container
        command: chmod 0600 /etc/letsencrypt/regru.ini

    - name: Run Certbot to obtain SSL certificates for {{ domain }} and *.{{ domain }}
      community.docker.docker_container_exec:
        container: certbot_container
        command: certbot certonly --authenticator dns -d {{ domain }} -d "*.{{ domain }}" --email {{ lets_encrypt_email }} --non-interactive --agree-tos --dns-propagation-seconds 900

    - name: Stop and remove the Docker container
      community.docker.docker_container:
        name: certbot_container
        state: absent
