---
- name: Setup NGINX Docker container with SSL and HTTP to HTTPS redirection
  hosts: all
  become: true

  vars:
    docker_network_name: docker-net
    docker_network_subnet: 172.20.0.0/16
    docker_network_range: 172.20.240.0/20
    nginx_image: "nginx:latest"
    nginx_conf_dir: "/etc/nginx/conf.d"
    letsencrypt_dir: "/etc/letsencrypt"
    restart_policy: "unless-stopped"

  tasks:
    - name: Create a network for nginx
      become: true
      docker_network:
        name: "{{ docker_network_name }}"
        ipam_config:
          - subnet: "{{ docker_network_subnet }}"
            iprange: "{{ docker_network_range }}"

    - name: Ensure the NGINX configuration directory exists
      file:
        path: "{{ nginx_conf_dir }}"
        state: directory

    - name: Deploy common NGINX configuration (common.conf)
      template:
        src: templates/common.conf.j2
        dest: "{{ nginx_conf_dir }}/common.conf"
        owner: root
        group: root
        mode: '0644'

    - name: Deploy Grafana NGINX configuration (grafana.conf)
      template:
        src: templates/grafana.conf.j2
        dest: "{{ nginx_conf_dir }}/grafana.conf"
        owner: root
        group: root
        mode: '0644'

    - name: Run NGINX Docker container
      docker_container:
        name: nginx
        image: "{{ nginx_image }}"
        state: started
        restart_policy: "{{ restart_policy }}"
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - "{{ letsencrypt_dir }}:/etc/letsencrypt"
          - "{{ nginx_conf_dir }}:/etc/nginx/conf.d"
        networks:
          - name: "{{ docker_network_name }}"
