---
- name: Install rsyslog packages
  apt:
    name:
      - rsyslog
      - logrotate
    state: present
    update_cache: true
  tags:
    - rsyslog
    - "rsyslog:packages"

- name: Configure rsyslog log rotation
  copy:
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: "0644"
    content: |
      /var/log/*log
      {
          weekly
          maxsize 500M
          rotate 6
          missingok
          notifempty
          compress
          delaycompress
          create 0640 syslog adm
          sharedscripts
          postrotate
              /usr/lib/rsyslog/rsyslog-rotate
          endscript
      }
  tags:
    - rsyslog
    - "rsyslog:config"

- name: Ensure rsyslog is enabled and started
  service:
    name: rsyslog
    enabled: true
    state: started
  tags:
    - rsyslog
    - "rsyslog:service"
