---
- name: Configure new machine
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  gather_facts: true

  roles:
    - apt_sources
    - hostname
    - tz
    - dns_client
    - ntp_client
    - role: ntp_server
      when: ntp_server_enabled | default(false) | bool
    - users
    - python3
    - iptables
    - utils
    - rsyslog
    - docker
    - zabbix_agent
    - ssh_keys
