---

- hosts: all
  become: true
  tasks:
  - name: Include secrets
    include_vars: secrets/common_secrets.yml

  - name: install atop
    apt:
      update_cache: yes

  - name: install atop
    apt:
      name: atop
      state: latest
