---

- hosts: all
  become: true
  tasks:
  - name: Include secrets
    include_vars: secrets/common_secrets.yml

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Debian"

  - name: add php support for appache
    apt:
      name: libapache2-mod-php
    when: ansible_distribution == "Debian"

