---
- hosts: all
  become: true
  vars:
    docker_network_name: docker-net
    docker_network_subnet: 172.20.0.0/16
    docker_network_range: 172.20.240.0/20

  tasks:
    - name: Create a network for owncloud
      become: true
      docker_network:
        name: "{{ docker_network_name }}"
        ipam_config:
          - subnet: "{{ docker_network_subnet }}"
            iprange: "{{ docker_network_range }}"

    - name: Owncloud
      community.docker.docker_container:
        name: owncloud
        image: "owncloud/server"
        networks:
          - name: "{{ docker_network_name }}"
        env:
          OWNCLOUD_DOMAIN: "{{ ip_address }}:1953"
        ports:
          - 1953:8080/tcp
        volumes:
          - /owncloud:/mnt/data:rw
        state: "started"
        restart_policy: "unless-stopped"

#Username/Password: admin/admin



# old server

# <?php
# $CONFIG = array (
#   'apps_paths' => 
#   array (
#     0 => 
#     array (
#       'path' => '/var/www/owncloud/apps',
#       'url' => '/apps',
#       'writable' => false,
#     ),
#     1 => 
#     array (
#       'path' => '/var/www/owncloud/custom',
#       'url' => '/custom',
#       'writable' => true,
#     ),
#   ),
#   'trusted_domains' => 
#   array (
#     0 => 'localhost',
#   ),
#   'datadirectory' => '/mnt/data/files',
#   'dbtype' => 'sqlite',
#   'dbhost' => '',
#   'dbname' => 'owncloud',
#   'dbuser' => '',
#   'dbpassword' => '',
#   'dbtableprefix' => 'oc_',
#   'log_type' => 'owncloud',
#   'supportedDatabases' => 
#   array (
#     0 => 'sqlite',
#     1 => 'mysql',
#     2 => 'pgsql',
#   ),
#   'upgrade.disable-web' => true,
#   'default_language' => 'en',
#   'overwrite.cli.url' => 'http://localhost:8080/',
#   'htaccess.RewriteBase' => '/',
#   'logfile' => '/mnt/data/files/owncloud.log',
#   'memcache.local' => '\\OC\\Memcache\\APCu',
#   'filelocking.enabled' => true,
#   'passwordsalt' => 'cyVHtQ/Nc2s/fjEncNkHnB5LD+sDBO',
#   'secret' => 'NyTdPfp8Nxx0imDN2MgsnBJQqAQwGrgKbI3kpZYr1oLCh83w',
#   'version' => '10.9.1.2',
#   'allow_user_to_change_mail_address' => '',
#   'logtimezone' => 'UTC',
#   'installed' => true,
#   'instanceid' => 'ocyg85nzzcrg',
# );
