---
- hosts: all
  become: true
  vars:
    zabbix_server_ip: 108.181.172.80

  tasks:
    - name: Add zabbix-agent2 on debian
      become: true
      when: ansible_distribution|lower == "debian"
      apt:
        deb: "https://repo.zabbix.com/zabbix/6.2/{{ ansible_distribution|lower }}/pool/main/z/zabbix-release/zabbix-release_6.2-4%2B{{ ansible_distribution|lower }}{{ ansible_distribution_major_version}}_all.deb"

    - name: Add zabbix-agent2 on ubuntu
      become: true
      when: ansible_distribution|lower == "ubuntu"
      apt:
        deb: "https://repo.zabbix.com/zabbix/6.2/{{ ansible_distribution|lower }}/pool/main/z/zabbix-release/zabbix-release_6.2-4%2B{{ ansible_distribution|lower }}{{ ansible_distribution_version}}_all.deb"

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install zabbix-agent2
      become: true
      apt:
        name:
          - zabbix-agent2
        state: present

    - name: Configure zabbix-agent2 server_active section
      lineinfile:
        dest: /etc/zabbix/zabbix_agent2.conf
        regexp: ^ServerActive=
        line: ServerActive={{ zabbix_server_ip }}

    - name: Configure hostname
      lineinfile:
        dest: /etc/zabbix/zabbix_agent2.conf
        regexp: ^Hostname=
        line: Hostname={{ ansible_hostname }}

    - name: add zabbix to docker group
      user:
        name: zabbix
        groups: docker
        append: yes

    # - name: add setfacl
    #   become: true
    #   apt:
    #     name:
    #       - acl
    #     state: present

    # - name: setfacl to docker socket
    #   ansible.posix.acl:
    #     path: /var/run/docker.sock
    #     entity: zabbix
    #     etype: user
    #     permissions: r
    #     state: present

    - name: Restart zabbix-agent2
      become: true
      service:
        name: zabbix-agent2
        state: restarted
