---
- hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install prereq
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
    
    - name: Add docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    
    - name: Download key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
    
    - name: Add docker repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/debian buster stable"
        state: present

    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes

    - name: Install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    
    - name: Install puthon3-docker for ansible mgmt
      apt:
        name:
          - python3-docker
          - python3-distutils
        state: present

