---
- hosts: all
  become: true
  vars:
    docker_network_name: docker-net
    docker_network_subnet: 172.20.0.0/16
    docker_network_range: 172.20.240.0/20

  tasks:
    - name: Create a network for ejabberd
      become: true
      docker_network:
        name: "{{ docker_network_name }}"
        ipam_config:
          - subnet: "{{ docker_network_subnet }}"
            iprange: "{{ docker_network_range }}"

    - name: install ejabberd
      community.docker.docker_container:
        name: ejabberd
        image: "ejabberd/ecs"
        networks:
          - name: "{{ docker_network_name }}"
        ports:
          - 1883:1883/tcp
          - 4369:4369/tcp
          - 5222:5222/tcp
          - 5269:5269/tcp
          - 5280:5280/tcp
          - 5443:5443/tcp
        volumes:
        # - /etc/containers/ejabberd_etc:/etc/ejabberd:rw
        # - /etc/containers/ejabberd_home:/home/ejabberd:rw
        # - /home/ejabberd:/etc/ejabberd:rw
        # - /home/database:/etc/ejabberd/database:rw
          - /home/ejabberd1:/home/ejabberd:rw
        state: "started"
        restart_policy: "unless-stopped"

    #- name: add vhosts file
    #  lineinfile:
    #    path: 

    # - name: set password
    #   shell: /bin/sh -c "sudo docker exec -it ejabberd bin/ejabberdctl register admin localhost ejabberd_Taran#32"
    #   ignore_errors: true

    # - name: set password
    #   shell: /bin/sh -c "sudo docker exec -it ejabberd bin/ejabberdctl register admin {{ item }} ejabberd_Taran#32"
    #   ignore_errors: true
    #   loop:
    #     - localhost
    #     - "{{ ip_address }}"
    #     - "{{ domain }}"


    # ^hosts:\n(^.*\n)+(?=loglevel:)

    # - name: set password
    #   community.docker.docker_container_exec:
    #     container: ejabberd
    #     argv:
    #      - /bin/sh
    #      - "-c"
    #      - "ejabberd bin/ejabberdctl register admin localhost ejabberd_Taran#32"

# Добавить домен 45.35.14.80:
#   sudo docker exec -it ejabberd sh
#   в файле /home/ejabberd/conf/ejabberd.yml добавить 
#     hosts:
#       - localhost
#       - 45.35.14.80
#   Рестарт сервиса: ./bin/ejabberdctl restart

# Добавить пользователей в новом домене через WEB-интерфейс (p3717 без указания @ и домена)

# user@vds4:~$ ls -la database/
# total 172
# drwxr-xr-x 3 9000 9000  4096 Mar  9 10:24 .
# drwxr-xr-x 7 user user  4096 Mar  9 10:21 ..
# drwxr-xr-x 4 9000 9000  4096 Mar  9 10:27 ejabberd@fcdad9e36abd
# -rw-r--r-- 1 9000 9000 15145 Mar  9 10:24 lite.new.sql
# -rw-r--r-- 1 9000 9000 13568 Mar  9 10:24 lite.sql
# -rw-r--r-- 1 9000 9000 24747 Mar  9 10:24 mssql.sql
# -rw-r--r-- 1 9000 9000 20005 Mar  9 10:24 mysql.new.sql
# -rw-r--r-- 1 9000 9000 14229 Mar  9 10:24 mysql.old-to-new.sql
# -rw-r--r-- 1 9000 9000 18017 Mar  9 10:24 mysql.sql
# -rw-r--r-- 1 9000 9000 25231 Mar  9 10:24 pg.new.sql
# -rw-r--r-- 1 9000 9000 14709 Mar  9 10:24 pg.sql
# user@vds4:~$ docker run -d --name ejabberd -v $(pwd)/database:/home/ejabberd/database ejabberd/ecs
