---
- hosts: all
  become: true
  vars:
    docker_network_name: docker-net
    docker_network_subnet: 172.20.0.0/16
    docker_network_range: 172.20.240.0/20

  tasks:
    - name: Include secrets
      include_vars: secrets/common_secrets.yml

    - name: Create a network for grafana
      become: true
      docker_network:
        name: "{{ docker_network_name }}"
        ipam_config:
          - subnet: "{{ docker_network_subnet }}"
            iprange: "{{ docker_network_range }}"

    - name: Create directory for Grafana configuration
      file:
        path: /etc/grafana
        state: directory
        owner: root
        group: root
        mode: '0770'

    - name: Install grafana
      community.docker.docker_container:
        name: grafana
        image: "grafana/grafana"
        networks:
          - name: "{{ docker_network_name }}"
        ports:
          - 3000:3000/tcp
        volumes:
          - /etc/grafana:/var/lib/grafana:rw
        state: "started"
        restart_policy: "unless-stopped"

# defalut login: admin/admin