---
- hosts: all
  become: true
  vars:
    zabbix_server_ip: 45.35.14.80

  tasks:
    - name: Add zabbix-agent2
      become: true
      apt:
        deb: https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bubuntu20.04_all.deb

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install zabbix-agent2
      become: true
      apt:
        name:
          - zabbix-agent2
        state: present

    - name: Configure zabbix-agent2 server_active section
      lineinfile:
        dest: /etc/zabbix/zabbix_agent2.conf
        regexp: ^ServerActive=
        line: ServerActive={{ zabbix_server_ip }}

    - name: Restart zabbix-agent2
      become: true
      service:
        name: zabbix-agent2
        state: restarted
