---
- hosts: all
  become: true
  vars:
    zabbix_server_ip: 45.35.14.80

  tasks:
    - name: Add zabbix-agent2
      become: true
      apt:
        deb: https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bdebian9_all.deb

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install zabbix-agent2
      become: true
      apt:
        name:
          - zabbix-agent2
        state: present

    - name: Configure zabbix-agent2 server_active section
      lineinfile:
        dest: /etc/zabbix/zabbix_agent2.conf
        regexp: ^ServerActive=
        line: ServerActive={{ zabbix_server_ip }}

    - name: add zabbix to docker group
      user:
        name: zabbix
        group: docker

    # - name: add setfacl
    #   become: true
    #   apt:
    #     name:
    #       - acl
    #     state: present

    # - name: setfacl to docker socket
    #   ansible.posix.acl:
    #     path: /var/run/docker.sock
    #     entity: zabbix
    #     etype: user
    #     permissions: r
    #     state: present

    - name: Restart zabbix-agent2
      become: true
      service:
        name: zabbix-agent2
        state: restarted
