---
- hosts: all
  become: true
  vars:
    zabbix_server_ip: "{{ zabbix_server_ip }}"

  tasks:
    - name: Include secrets
      include_vars: secrets/common_secrets.yml

    - name: Include secrets
      include_vars: secrets/common_secrets.yml

    - name: Add zabbix-agent2 on debian
      become: true
      when: ansible_distribution|lower == "debian"
      apt:
        deb: "https://repo.zabbix.com/zabbix/6.4/{{ ansible_distribution|lower }}/pool/main/z/zabbix-release/zabbix-release_6.4-1%2B{{ ansible_distribution|lower }}{{ ansible_distribution_major_version}}_all.deb"

    - name: Add zabbix-agent2 on ubuntu
      become: true
      when: ansible_distribution|lower == "ubuntu"
      apt:
        deb: "https://repo.zabbix.com/zabbix/6.4/{{ ansible_distribution|lower }}/pool/main/z/zabbix-release/zabbix-release_6.4-4%2B{{ ansible_distribution|lower }}{{ ansible_distribution_version}}_all.deb"

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install zabbix-agent2
      become: true
      apt:
        name:
          - zabbix-agent2
        state: present

    - name: Configure zabbix-agent2 server_active section
      lineinfile:
        dest: /etc/zabbix/zabbix_agent2.conf
        regexp: ^ServerActive=
        line: ServerActive={{ zabbix_server_ip }}

    - name: Configure hostname
      lineinfile:
        dest: /etc/zabbix/zabbix_agent2.conf
        regexp: ^Hostname=
        line: Hostname={{ ansible_hostname }}

    - name: Configure hostname
      lineinfile:
        dest: /etc/zabbix/zabbix_agent2.conf
        line: AllowKey=system.run[*]

    - name: add zabbix to docker group
      user:
        name: zabbix
        groups: docker
        append: yes

    - name: add setfacl
      become: true
      apt:
        name:
          - acl
        state: present

    - name: setfacl to docker socket
      ansible.posix.acl:
        path: /var/run/docker.sock
        entity: zabbix
        etype: user
        permissions: r
        state: present

    - name: Restart zabbix-agent2
      become: true
      service:
        name: zabbix-agent2
        state: restarted

    - name: Create a host in zabbix
      vars:
        ansible_host: "zabbix.vds2.space"
        ansible_zabbix_url_path: ""
        ansible_network_os: "community.zabbix.zabbix"
        ansible_connection: "httpapi"
        ansible_user: "api_user"
        ansible_httpapi_pass: "api_{{ common_passwd }}"
      become: false
      community.zabbix.zabbix_host:
        host_name: "{{ ansible_hostname }}"
        visible_name: "{{ ansible_hostname }}"
        host_groups:
          - "Linux servers"
        link_templates:
          - "Linux by Zabbix agent active"
          - "Docker by Zabbix agent 2 active"
        status: enabled
        state: present
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "127.0.0.1"
            dns: ""
            port: "10050"
