---
- hosts: all
  become: true
  tasks:
    # - name: Set the policy for the INPUT chain to DROP
    #   ansible.builtin.iptables:
    #     chain: INPUT
    #     policy: ACCEPT

    # - name: Iptables flush filter
    #   ansible.builtin.iptables:
    #     chain: "{{ item }}"
    #     flush: yes
    #   with_items: ["INPUT", "FORWARD", "OUTPUT"]

    - name: Allow new incoming from localhost
      ansible.builtin.iptables:
        chain: INPUT
        source: 127.0.0.0/8
        jump: ACCEPT

    - name: Allow related and established connections
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    # - name: Allow new incoming on TCP port 19022 (SSH)
    #   ansible.builtin.iptables:
    #     chain: INPUT
    #     protocol: tcp
    #     destination_port: 19022
    #     jump: ACCEPT
    #     comment: Accept SSH

    # - name: Allow new incoming on TCP port 80
    #   ansible.builtin.iptables:
    #     chain: INPUT
    #     protocol: tcp
    #     destination_port: 80
    #     jump: ACCEPT
    #     comment: Accept HTTP

    # - name: Allow new incoming on TCP port 443
    #   ansible.builtin.iptables:
    #     chain: INPUT
    #     protocol: tcp
    #     destination_port: 443
    #     jump: ACCEPT
    #     comment: Accept HTTPs

    # - name: Allow new incoming on TCP port 1953
    #   ansible.builtin.iptables:
    #     chain: INPUT
    #     protocol: tcp
    #     destination_port: 1953
    #     jump: ACCEPT
    #     comment: Accept HTTP

    - name: Allow new incoming on UDP port 1701
      ansible.builtin.iptables:
        chain: INPUT
        protocol: udp
        destination_port: 1701
        jump: ACCEPT
        comment: Accept L2TP

    - name: Allow new incoming from 10.0.0.0/11
      ansible.builtin.iptables:
        chain: INPUT
        source: 10.0.0.0/11
        jump: ACCEPT
        comment: Accept internal network

    - name: Allow GRE from list
      ansible.builtin.iptables:
        chain: INPUT
        source: "{{ item }}"
        protocol: GRE
        jump: ACCEPT
        comment: Accept GRE from my hosts
      with_items:
        [
          "45.141.102.72",
          "45.35.14.80",
          "172.107.174.18",
          "86.110.170.70",
          "213.138.67.146",
        ]

    - name: Allow connections on multiple ports
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_ports:
          - "80"
          - "443"
          - "19022"
          - "1953"
          - "3000"
          - "5222"
          - "5269"
          - "5280"
          - "5443"

        jump: ACCEPT

    - name: DROP output to 10.0.0.0/11 not through tunnels
      ansible.builtin.iptables:
        chain: OUTPUT
        destination: 10.0.0.0/11
        out_interface: eth0
        jump: DROP
        comment: Drop packets to my network not from tunnels

    - name: Set the policy for the INPUT chain to DROP
      ansible.builtin.iptables:
        chain: INPUT
        policy: DROP
