---
- name: Configure new machine
  hosts: "{{ hosts | default('all') }}"
  become: true
  gather_facts: true

  roles:
    - role: tz
      tags: tz
    - role: dns_client
      tags: dns_client
    - role: ntp_client
      tags: ntp_client
    - role: users
      tags: users
    - role: python3
      tags: python3
    - role: iptables
      tags: iptables
    - role: utils
      tags: utils
    - role: rsyslog
      tags: rsyslog
    - role: docker
      tags: docker
    - role: zabbix_agent
      tags: zabbix_agent
    - role: ssh_keys
      tags: ssh_keys
