---
- name: Configure new machine
  hosts: "{{ hosts | default('all') }}"
  become: true
  gather_facts: true

  roles:
    - tz
    - dns_client
    - ntp_client
    - users
    - python3
    - iptables
    - utils
    - rsyslog
    - docker
    - zabbix_agent
    - ssh_keys
