---
- name: Check DNS resolution
  ansible.builtin.command: "getent hosts {{ k8s_resolv_check_host }}"
  changed_when: false
  tags:
    - prepare_k8s_hosts
    - "prepare_k8s_hosts:validate"

- name: Disable active swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb | int > 0
  changed_when: true
  tags:
    - prepare_k8s_hosts
    - "prepare_k8s_hosts:swap"

- name: Disable swap in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#]\S+\s+\S+\s+swap\s+.*)$'
    replace: '# \1'
  tags:
    - prepare_k8s_hosts
    - "prepare_k8s_hosts:swap"

- name: Configure Kubernetes kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      {% for module in k8s_kernel_modules %}
      {{ module }}
      {% endfor %}
  tags:
    - prepare_k8s_hosts
    - "prepare_k8s_hosts:kernel"

- name: Load Kubernetes kernel modules
  ansible.builtin.command: "modprobe {{ item }}"
  changed_when: false
  loop: "{{ k8s_kernel_modules }}"
  tags:
    - prepare_k8s_hosts
    - "prepare_k8s_hosts:kernel"

- name: Configure Kubernetes sysctl settings
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
  loop: "{{ k8s_sysctl_settings | dict2items }}"
  tags:
    - prepare_k8s_hosts
    - "prepare_k8s_hosts:sysctl"
