---
k8s_master_group: masters
k8s_join_source_master: "{{ groups[k8s_master_group][0] }}"
k8s_api_port: 6443
k8s_load_balancer_port: 8443
k8s_kubeconfig_path: /etc/kubernetes/admin.conf
k8s_keepalived_router_id: 51
k8s_keepalived_auth_pass: k8sHaPass
k8s_keepalived_interface: "{{ ansible_default_ipv4.interface | default('eth0') }}"
k8s_haproxy_stats_port: 8404
k8s_kubeadm_ignore_preflight_errors: ""
k8s_kubeadm_join_token_ttl: 2h
k8s_add_master_copy_certs_manually: true
k8s_pki_dir: /etc/kubernetes/pki
k8s_control_plane_cert_files:
  - ca.crt
  - ca.key
  - sa.pub
  - sa.key
  - front-proxy-ca.crt
  - front-proxy-ca.key
k8s_optional_control_plane_cert_files:
  - external-etcd.crt
  - external-etcd.key
  - apiserver-etcd-client.crt
  - apiserver-etcd-client.key
