---
- name: Build and run SoftEther VPN Server Docker container
  hosts: all
  become: true
  collections:
    - community.docker
  tasks:
    - name: Ensure Docker Python module is installed
      pip:
        name: docker
        state: present

    - name: Create directory for Docker build context
      file:
        path: /tmp/softether_docker
        state: directory

    - name: Create Dockerfile
      copy:
        dest: /tmp/softether_docker/Dockerfile
        content: |
          # Use Ubuntu 24.04 as base image
          FROM ubuntu:24.04

          # Install required packages
          RUN apt-get update && \
              apt-get install -y wget make gcc binutils && \
              apt-get clean

          # Download and extract SoftEther VPN Server
          WORKDIR /tmp
          RUN wget http://www.softether-download.com/files/softether/v4.42-9798-rtm-2023.06.30-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-v4.42-9798-rtm-2023.06.30-linux-x64-64bit.tar.gz && \
              tar -xzf softether-vpnserver-v4.42-9798-rtm-2023.06.30-linux-x64-64bit.tar.gz && \
              cd vpnserver && \
              yes 1 | make

          # Move the vpnserver to /usr/local and set proper permissions
          RUN mv vpnserver /usr/local/ && \
              chmod -R 600 /usr/local/vpnserver/* && \
              chmod 700 /usr/local/vpnserver/vpnserver && \
              chmod 700 /usr/local/vpnserver/vpncmd

          # Expose necessary ports
          EXPOSE 443/tcp 992/tcp 1194/udp 5555/tcp

          # Start SoftEther VPN server
          CMD ["/usr/local/vpnserver/vpnserver", "execsvc"]

    - name: Build Docker image
      docker_image:
        name: softether-vpn-server
        path: /tmp/softether_docker
        state: present

    - name: Run Docker container
      docker_container:
        name: sst-server
        image: softether-vpn-server
        state: started
        restart_policy: always
        ports:
          - "443:443"
          - "992:992"
          - "1194:1194/udp"
          - "5555:5555"
