---
containerd_package: containerd
containerd_config_dir: /etc/containerd
containerd_config_file: /etc/containerd/config.toml
containerd_systemd_cgroup: true
containerd_proxy_enabled: "{{ kubernetes_use_controller_proxy | default(false) }}"
containerd_proxy_url: "http://127.0.0.1:{{ kubernetes_target_proxy_port | default(18080) }}"
containerd_proxy_no_proxy:
  - 127.0.0.1
  - localhost
  - "{{ k8s_service_subnet }}"
  - "{{ k8s_pod_subnet }}"
containerd_systemd_dropin_dir: /etc/systemd/system/containerd.service.d
containerd_use_nexus: "{{ use_nexus | default(false) }}"
containerd_nexus_registry: "{{ nexus_docker_registry | default('') }}"
containerd_nexus_elastic_registry: "{{ nexus_elastic_registry | default('') }}"
containerd_nexus_k8s_registry: "{{ nexus_k8s_registry | default('') }}"
