---
- hosts: all
  become: true

  tasks:
    - name: Create nginx directory if it does not exist
      ansible.builtin.file:
        path: //etc/nginx/conf.d/
        state: directory

    - name: Synchronize config files
      ansible.builtin.synchronize:
        src: conf.d/
        dest: /etc/nginx/conf.d/
        recursive: yes
        delete: yes
        rsync_opts:
          - "--checksum"

    - name: nginx_proxy_container
      community.docker.docker_container:
        name: nginx_proxy
        image: "nginx"
        network_mode: host
        env:
          TZ: "America/Chicago"
          LETSENCRYPT: "true"
          LE_EMAIL: "example@example.com"
          LE_FQDN: "vds4.online"
        ports:
          - 80:80/tcp
          - 443:443/tcp
        volumes:
          - /etc/nginx/conf.d:/etc/nginx/conf.d:rw
          - /etc/ssl:/etc/nginx/ssl:rw
        state: "started"
        restart_policy: "unless-stopped"

    - name: Reload NGINX configuration
      ansible.builtin.command:
        cmd: docker exec nginx_proxy nginx -s reload