---
- name: Configure loopback bridges on main routers
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    routers:
      - {identity: vds7_CHR, address: 10.255.0.7}
      - {identity: K16_112, address: 10.255.0.112}
      - {identity: 3Ekipazhnyi64, address: 10.255.0.64}
      - {identity: k16_21, address: 10.255.0.21}
      - {identity: Misha, address: 10.255.0.24}
  tasks:
    - name: Configure each router
      ansible.builtin.include_tasks: loopback-client.yml
      loop: "{{ routers }}"
      loop_control:
        loop_var: router
