---
- name: Create etcd cluster
  hosts: "{{ hosts | default('etcd') }}"
  become: true
  gather_facts: true
  vars_files:
    - ../group_vars/k8s_k112.yml

  roles:
    - apt_sources
    - ../roles/create_etcd_cluster
