---
- name: Configure Kubernetes Master Node
  hosts: master
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install required packages
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - gnupg2
          - gpg
          - sudo
        state: present

    - name: Disable swap and comment out in /etc/fstab
      shell: |
        swapoff -a
        sed -i '/ swap / s/^/#/' /etc/fstab
      tags: disable_swap

    - name: Remove swap file
      file:
        path: /swap.img
        state: absent

    - name: Load necessary kernel modules
      shell: |
        modprobe overlay -v
        modprobe br_netfilter -v

    - name: Add kernel modules to /etc/modules
      lineinfile:
        path: /etc/modules
        line: "{{ item }}"
        state: present
      with_items:
        - overlay
        - br_netfilter

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        sysctl_set: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes GPG key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

    - name: Add Kubernetes repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list

    - name: Update apt cache for Kubernetes
      apt:
        update_cache: yes

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Mark Kubernetes packages on hold
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        mark: hold

    - name: Install containerd
      apt:
        name:
          - containerd.io
        state: present

    - name: Configure containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default | tee /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Restart containerd
      systemd:
        name: containerd
        enabled: yes
        state: restarted

    - name: Initialize Kubernetes master node
      shell: |
        kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Set up kubectl for the root user
      copy:
        dest: "{{ item.dest }}"
        content: "{{ lookup('file', item.src) }}"
      with_items:
        - { src: '/etc/kubernetes/admin.conf', dest: '/root/.kube/config' }

    - name: Deploy Flannel pod network
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      args:
        executable: /bin/bash
