---
- name: Configure Kubernetes Master Node
  hosts: master
  become: yes

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade all packages (dist upgrade)
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - gnupg2
          - gpg
          - sudo
          - curl
        state: present
        update_cache: yes

    - name: Disable swap
      command: swapoff -a

    - name: Comment out swap in /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^([^#].*swap.*)'
        line: '#\1'

    - name: Remove swap file
      file:
        path: /swap.img
        state: absent

    - name: Load overlay kernel module
      modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter kernel module
      modprobe:
        name: br_netfilter
        state: present

    - name: Ensure overlay is configured to load at boot
      lineinfile:
        path: /etc/modules
        line: "overlay"
        create: yes
        state: present

    - name: Ensure br_netfilter is configured to load at boot
      lineinfile:
        path: /etc/modules
        line: "br_netfilter"
        create: yes
        state: present

    - name: Enable IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        dest: /tmp/k8s-release.key

    - name: Dearmor and store the Kubernetes GPG key
      command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/k8s-release.key

    - name: Add Kubernetes repo
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        state: present

    - name: Update APT cache after adding Kubernetes repo
      apt:
        update_cache: yes

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Hold kubelet, kubeadm, and kubectl at current version
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: hold

    - name: Enable and start kubelet service
      systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Install containerd
      apt:
        name:
          - containerd.io
        state: present

    - name: Configure containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default | tee /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Restart containerd
      systemd:
        name: containerd
        enabled: yes
        state: restarted

    - name: Initialize Kubernetes master node
      shell: |
        kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Set up kubectl for the root user
      copy:
        dest: "{{ item.dest }}"
        content: "{{ lookup('file', item.src) }}"
      with_items:
        - { src: '/etc/kubernetes/admin.conf', dest: '/root/.kube/config' }

    - name: Deploy Flannel pod network
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      args:
        executable: /bin/bash
