---
- name: Install Kubernetes Worker Node
  hosts: workers
  become: yes
  tasks:
    - name: Disable swap
      command: swapoff -a

    - name: Comment out swap entries in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#]*\s+swap\s+.*)$'
        replace: '# \1'

    - name: Load kernel modules
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          overlay

    - name: Ensure kernel modules are loaded
      shell: |
        modprobe br_netfilter
        modprobe overlay

    - name: Set sysctl parameters
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1

    - name: Apply sysctl parameters
      command: sysctl --system

    - name: Install containerd
      apt:
        name: containerd
        state: present
        update_cache: yes

    - name: Configure containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Restart and enable containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Install required packages for Kubernetes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: Add Kubernetes GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install kubelet and kubeadm
      apt:
        name:
          - kubelet
          - kubeadm
        state: present
        update_cache: yes

    - name: Hold kubelet and kubeadm at current version
      shell: |
        apt-mark hold kubelet kubeadm

    # Note: The worker nodes are not joined to the cluster in this playbook.
