---
- hosts: all
  become: true
  vars:
    docker_network_name: docker-net
    docker_network_subnet: 172.20.0.0/16
    docker_network_range: 172.20.240.0/20

  tasks:
    - name: Include secrets
      include_vars: secrets/common_secrets.yml

    - name: Create a network for gitlab
      become: true
      docker_network:
        name: "{{ docker_network_name }}"
        ipam_config:
          - subnet: "{{ docker_network_subnet }}"
            iprange: "{{ docker_network_range }}"

    - name: gitlab
      community.docker.docker_container:
        name: gitlab
        image: "gitlab/gitlab-ce:16.5.8-ce.0"
        memory: "4g"
        networks:
          - name: "{{ docker_network_name }}"
        env:
          hostname:  "{{ inventory_hostname }}"
          shm-size: "256m"
        ports:
          - 1443:443/tcp
          - 8081:80/tcp
          - 2222:22/tcp
        volumes:
          - /storage/gitlab/config:/etc/gitlab:rw
          - /storage/gitlab/logs:/var/log/gitlab:rw
          - /storage/gitlab/data:/var/opt/gitlab:rw
        state: "started"
        restart_policy: "unless-stopped"

# old server

# <?php
# $CONFIG = array (
#   'apps_paths' => 
#   array (
#     0 => 
#     array (
#       'path' => '/var/www/gitlab/apps',
#       'url' => '/apps',
#       'writable' => false,
#     ),
#     1 => 
#     array (
#       'path' => '/var/www/gitlab/custom',
#       'url' => '/custom',
#       'writable' => true,
#     ),
#   ),
#   'trusted_domains' => 
#   array (
#     0 => 'localhost',
#   ),
#   'datadirectory' => '/mnt/data/files',
#   'dbtype' => 'sqlite',
#   'dbhost' => '',
#   'dbname' => 'gitlab',
#   'dbuser' => '',
#   'dbpassword' => '',
#   'dbtableprefix' => 'oc_',
#   'log_type' => 'gitlab',
#   'supportedDatabases' => 
#   array (
#     0 => 'sqlite',
#     1 => 'mysql',
#     2 => 'pgsql',
#   ),
#   'upgrade.disable-web' => true,
#   'default_language' => 'en',
#   'overwrite.cli.url' => 'http://localhost:8080/',
#   'htaccess.RewriteBase' => '/',
#   'logfile' => '/mnt/data/files/gitlab.log',
#   'memcache.local' => '\\OC\\Memcache\\APCu',
#   'filelocking.enabled' => true,
#   'passwordsalt' => 'cyVHtQ/Nc2s/fjEncNkHnB5LD+sDBO',
#   'secret' => 'NyTdPfp8Nxx0imDN2MgsnBJQqAQwGrgKbI3kpZYr1oLCh83w',
#   'version' => '10.9.1.2',
#   'allow_user_to_change_mail_address' => '',
#   'logtimezone' => 'UTC',
#   'installed' => true,
#   'instanceid' => 'ocyg85nzzcrg',
# );
