---
- name: Deploy L2TP-only Docker Container
  hosts: all
  become: yes

  tasks:
    - name: Ensure Docker is installed (Debian/Ubuntu example)
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Create /etc/l2tp directory on host
      file:
        path: /etc/l2tp
        state: directory
        mode: '0755'

    - name: Copy Dockerfile
      copy:
        src: Dockerfile
        dest: /etc/l2tp/Dockerfile
        mode: '0644'

    - name: Copy entrypoint.sh
      copy:
        src: entrypoint.sh
        dest: /etc/l2tp/entrypoint.sh
        mode: '0755'

    - name: Copy chap-secrets
      copy:
        src: chap-secrets
        dest: /etc/l2tp/chap-secrets
        mode: '0600'

    - name: Copy xl2tpd.conf
      copy:
        src: xl2tpd.conf
        dest: /etc/l2tp/xl2tpd.conf
        mode: '0644'

    - name: Build L2TP Docker image
      docker_image:
        name: l2tp
        tag: latest
        state: present
        source: build
        build:
          path: /etc/l2tp

    - name: Run L2TP container
      docker_container:
        name: l2tp
        image: l2tp:latest
        state: started
        restart_policy: always
        privileged: yes
        published_ports:
          - "1701:1701/udp"
        volumes:
          - /etc/l2tp/chap-secrets:/etc/ppp/chap-secrets:ro
          - /etc/l2tp/xl2tpd.conf:/etc/xl2tpd/xl2tpd.conf:ro
