---
elk_version: "8.17.3"
elk_install_dir: /opt/elk
elk_network_name: elk
elk_elasticsearch_image: "docker.elastic.co/elasticsearch/elasticsearch:{{ elk_version }}"
elk_logstash_image: "docker.elastic.co/logstash/logstash:{{ elk_version }}"
elk_kibana_image: "docker.elastic.co/kibana/kibana:{{ elk_version }}"
elk_elasticsearch_port: 9200
elk_kibana_port: 5601
elk_beats_port: 5044
elk_elasticsearch_memory: 2g
elk_logstash_memory: 1g
elk_kibana_memory: 1g

# Optionally make Kibana use the same authenticated forward proxy as Nexus
# when downloading Fleet integrations from the Elastic Package Registry.
elk_kibana_integrations_use_proxy: false
elk_kibana_integrations_proxy_endpoint: "{{ squid_endpoint | default('') }}"
elk_kibana_integrations_proxy_user: "{{ squid_user | default('') }}"
elk_kibana_integrations_proxy_password: "{{ squid_pass | default('') }}"
