---
service_containers:
  - speedtest
  - socks5
  - certbot
  - nginx
  - zabbix_proxy

zabbix_proxy_hostname: vds1
zabbix_proxy_server_host: 217.144.189.206
zabbix_proxy_server_port: 10051
zabbix_proxy_tls_psk_identity: vds1
zabbix_agent_deya_solar_enabled: true

wireguard_enabled: true
wireguard_interface: wg0
wireguard_address: 10.250.1.7/32
wireguard_listen_port: 56685
wireguard_private_key: "{{ wireguard_server_private_key }}"
wireguard_peers:
  - name: vds7
    public_key: /COMR2JjUcrx6kyrsVb6rGIvQgCr0oQ26t5A33o+ohk=
    endpoint: 62.60.216.73:56697
    allowed_ips:
      - 10.250.7.1/32

domain: vds1.space
second_octet: 19
l2tp_octet: 255
gre_octet: 254
subdomains_ports:
  - speedtest:3005
  - grafana:3000
