---
service_containers:
  - speedtest
  - socks5
  - ejabberd
  - gitlab
  - gitlab_runner
  - jenkins
  - squid
  - owncloud
  - certbot
  - nginx

second_octet: 22
wg_octet: 253
gre_octet: 254
l2tp_octet: 255
domain: vds06.space

wireguard_vds7:
  interface: wg0
  address: 10.250.1.6/32
  old_address: 10.250.6.7/32
  old_remote_address: 10.250.7.6
  remote_address: 10.250.1.7
  public_key: UXPiRL2G6vovV1i838Z69J0bNBsUoXWTznsQ5+bNXHY=
  port: 56696
