---
service_containers:
  - speedtest
  - socks5
  - mtproto_pmikle_proxy
  - ejabberd
  - certbot
  - nginx
  - zabbix_proxy

zabbix_proxy_hostname: vds8
zabbix_proxy_server_host: 217.144.189.206
zabbix_proxy_server_port: 10051
zabbix_proxy_tls_psk_identity: vds8
zabbix_agent_deya_solar_enabled: true
auditbeat_elastic_apt_repo_enabled: false

wireguard_enabled: true
wireguard_interface: wg0
wireguard_addresses:
  - 10.250.8.7/32
  - 10.250.8.1/32
wireguard_listen_port: 56699
wireguard_private_key: "{{ wireguard_server_private_key }}"
wireguard_peers:
  - name: vds7
    public_key: WHc5K+biGIULJ9YNAuv6XeiyWkUSivZ12FZxMMx2ewA=
    endpoint: 62.60.216.73:56699
    allowed_ips:
      - 10.250.7.8/32
  - name: mikrotik-3Ekipazhnyi64
    public_key: rUX5DJTmbbehlI6gchyOyWwaZ80nBz6dXI1KdpFlum8=
    source_address: 10.250.8.1
    allowed_ips:
      - 10.250.108.1/32
      - 10.10.0.0/16

second_octet: 20
wg_octet: 253
gre_octet: 254
l2tp_octet: 255
domain: vds08.space
