---
- hosts: wireguard_servers
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes
      tags: update

    - name: Find the default network interface
      set_fact:
        wg_interface: "{{ ansible_default_ipv4.interface }}"

    - name: Purge WireGuard and remove WireGuard directory
      block:
        - name: Purge WireGuard package
          apt:
            name: wireguard
            state: absent
            purge: yes

        - name: Remove WireGuard directory
          file:
            path: /etc/wireguard
            state: absent
      tags: purge

    - name: Delete WireGuard interface wg0
      command: ip link del wg0
      ignore_errors: yes
      tags: cleanup

    - name: Install WireGuard
      apt:
        name: wireguard
        state: present
        update_cache: yes

    - name: Ensure the WireGuard directory exists
      file:
        path: /etc/wireguard
        state: directory
        mode: '0700'

    - name: Generate private key
      command: wg genkey
      register: wg_private_key
      changed_when: false

    - name: Generate public key
      shell: echo "{{ wg_private_key.stdout }}" | wg pubkey
      register: wg_public_key
      changed_when: false

    - name: Create WireGuard config
      template:
        src: wireguard.conf.j2
        dest: /etc/wireguard/wg0.conf
        mode: '0600'
      notify: Restart WireGuard

    - name: Enable and start WireGuard
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started

    - name: copy add_peer.sh script
      copy:
        src: add_peer.sh
        dest: /etc/wireguard
        owner: root
        group: root
        mode: "0640"

  handlers:
    - name: Restart WireGuard
      systemd:
        name: wg-quick@wg0
        state: restarted
