---
- hosts: wireguard_servers
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Install WireGuard
      apt:
        name: wireguard
        state: present
        update_cache: yes

    - name: Ensure the WireGuard directory exists
      file:
        path: /etc/wireguard
        state: directory
        mode: '0700'

    - name: Generate private key
      command: wg genkey
      register: wg_private_key
      changed_when: false

    - name: Generate public key
      shell: echo "{{ wg_private_key.stdout }}" | wg pubkey
      register: wg_public_key
      changed_when: false

    - name: Create WireGuard config
      template:
        src: wireguard.conf.j2
        dest: /etc/wireguard/wg0.conf
        mode: '0600'
      notify: Restart WireGuard

    - name: Enable and start WireGuard
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started

  handlers:
    - name: Restart WireGuard
      systemd:
        name: wg-quick@wg0
        state: restarted
